---
- name: system facts
  hosts: all
#  gather_facts: no
  tasks:

    - name: display hostname
      debug: 
        msg: |
          "The server name {{ ansible_hostname}}
          The address is {{ ansible_default_ipv4.address }}" 


