---
# tasks file for myapache
#
- name: install apache packages
  yum: 
    name: httpd
    state: latest

- name: copy templates
  template: 
    src: apache_httpdconf.j2
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: 0444 
  notify: 
    - restart apache
  when: apache_enable 

- name: copy templates
  template: 
    src: apache_indexhtml.j2
    dest: /var/www/html/index.html 
    owner: root
    group: root
    mode: 0444 
  when: apache_enable 

- name: start services
  service: 
    name: httpd
    state: restarted
    enabled: true
  when: apache_enable 

- name: start firewalld
  service: 
    name: firewalld
    state: restarted
    enabled: true
  when: apache_enable 

- name: open firewall port 
  firewalld: 
    port: 80/tcp
    immediate: true
    permanent: true
    state: enabled
  when: apache_enable 

