---
- name: Enable intrate services
  hosts: servera.lab.example.com
  remote_user: devops
  become: yes

  tasks: 
    - name: latest version of httpd and firewalld insatlled
      yum: 
        name: 
          - httpd
          - firewalld
        state: latest
    
    - name: firewalld enabled and running
      service: 
        name: firewalld
        enabled: true
        state: started

    - name: firewalld permits http service
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes

    - name: httpd enabled and running
      service: 
        name: httpd
        enabled: true
        state: started

    - name: teest html page is installed
      copy:
        content: "Welcome to the example.com intranet\n"
        dest: /var/www/html/index.html 

- name: test intarnet web service
  hosts: localhost
  remote_user: devops
  become: no

  tasks:
    - name: connect to intranet web server
      uri:
        url: http://servera.lab.example.com
        status_code: 200

...
