---
- shell: rpm -q httpd
  register: output
  failed_when: rpm_check.rc = 1

- block: 
  - get_url: 
    url: "{{ https_url }}" 
    dest: /etc/httpd/conf.d/

  - file: 
    path: /etc/httpd/conf.d/ssl 
    state: directory
    mode: 0755

  - file: 
    path: /var/www/httpd/log
    state: directory
    mode: 0755

  - stat: 
      path: /etc/httpd/conf.d/ssl.conf
    register: ssl_file

  - shell: 
      mv /etc/httpd/conf.d/ssl.conf /etc/httpd/conf.d/ssl.conf.bak
    when: 
      ssl_file.stat.exists

  - unarchiv: 
      src: "{{ ssl_uri }}"
      dest: /etc/httpd/conf.d/ssl
      copy: no
    notify: 
      - restart_services

  - copy: 
      content: "{{ ansible_fqdn }} ({{ ansible_default_ipv4.address }}) has been customiyed by Ansible\n" 
      dest: /var/www/html/index.html 

  when: 
    rpm_check.rc == 0

...
