---
- name: install httpd package
  yum: 
    name: httpd
    state: present

- name: start and enable httpd
  service: 
    name: httpd
    state: started
    enabled: true

- name: download html content
  copy: 
    src: html/
    dest: "/var/www/vhosts/{{ ansible_hostname }}"

- name: install template config file to webserver 
  template: 
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: 0644
  notify: 
    - restart httpd
...
